import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: forge_gradle_version, changing: true
    }
}

plugins {
    id 'com.github.johnrengelman.shadow' version "${shadow_gradle_version}"
}

apply plugin: 'net.minecraftforge.gradle'

group = 'alexiil.mc.mod.load'
version = mod_version

java {
    archivesBaseName = 'CustomLoadingScreen'
    toolchain.languageVersion = JavaLanguageVersion.of(8)
}

configurations {
    shade
    implementation.extendsFrom(shade)
}

minecraft {
    mappings channel: "$mappings_channel", version: "$mappings_version"

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'fml.coreMods.load', 'alexiil.mc.mod.load.coremod.ClsPlugin'

            mods {
                customloadingscreen {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven { url = 'https://mod-buildcraft.com/maven' }
    flatDir { dirs 'libs' }
}

dependencies {
    minecraft "net.minecraftforge:forge:$minecraft_version-$forge_version"

    shade name: 'buildcraft-libexpression-0.9.3-pre.4'

    testImplementation 'junit:junit:4.12'
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', "$minecraft_version"

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': "$minecraft_version"
        duplicatesStrategy DuplicatesStrategy.INCLUDE
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
        duplicatesStrategy DuplicatesStrategy.INCLUDE
    }
}

jar {
    archiveClassifier.set('slim')
    manifest {
        attributes([
                'Specification-Title'        : 'CustomLoadingScreen',
                'Specification-Vendor'       : 'AlexIIL',
                'Specification-Version'      : '1',
                'Implementation-Title'       : 'CustomLoadingScreen',
                'Implementation-Version'     : project.version,
                'Implementation-Vendor'      : 'AlexIIL',
                'Implementation-Timestamp'   : new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'FMLCorePluginContainsFMLMod': true,
                'FMLCorePlugin'              : 'alexiil.mc.mod.load.coremod.ClsPlugin',
                'ForceLoadAsMod'             : true
        ])
    }
    duplicatesStrategy DuplicatesStrategy.INCLUDE
}

tasks.withType(ShadowJar).configureEach {
    archiveClassifier.set('')
    configurations = [project.configurations.shade]
    relocate 'buildcraft.lib.expression', 'alexiil.mc.mod.load.repackage.buildcraft.lib.expression'
    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA', 'META-INF/INDEX.LIST'
    manifest {
        attributes jar.manifest.attributes
    }
    duplicatesStrategy DuplicatesStrategy.INCLUDE
}

afterEvaluate {
    tasks.findByName('prepareRuns')?.dependsOn('processResources')
    tasks.findByName('prepareRuns')?.doLast {
        copy {
            from "$buildDir/resources/main"
            into "$buildDir/classes/java/main"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

reobf {
    shadowJar {}
}
